//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Authentication
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Authentication.IAuthent" +
        "icationSoapEndpointService")]
    public interface IAuthenticationSoapEndpointService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IAuthenticationSoapEndpointService/Login", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Authentication.LoginResponse> LoginAsync(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Authentication.LoginRequest1 request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IAuthenticationSoapEndpointService/ResetPasswordStep1", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Authentication.ResetPasswordStep1Response> ResetPasswordStep1Async(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Authentication.ResetPasswordStep1Request request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IAuthenticationSoapEndpointService/ResetPasswordStep2", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Authentication.ResetPasswordStep2Response> ResetPasswordStep2Async(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Authentication.ResetPasswordStep2Request request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class LoginRequest
    {

        private string emailField;

        private string passwordField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class Unit
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class ResetPasswordRequest
    {

        private string tokenField;

        private string passwordField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class SendResetPasswordRequest
    {

        private string emailField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class JwtTokenModel
    {

        private string tokenField;

        private string leaseField;

        private System.DateTime validToField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration", Order = 1)]
        public string Lease
        {
            get
            {
                return this.leaseField;
            }
            set
            {
                this.leaseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public System.DateTime ValidTo
        {
            get
            {
                return this.validToField;
            }
            set
            {
                this.validToField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "Login", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class LoginRequest1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Authentication.LoginRequest model;

        public LoginRequest1()
        {

        }

        public LoginRequest1(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Authentication.LoginRequest model)
        {
            this.model = model;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "LoginResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class LoginResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Authentication.JwtTokenModel LoginResult;

        public LoginResponse()
        {
        }

        public LoginResponse(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Authentication.JwtTokenModel LoginResult)
        {
            this.LoginResult = LoginResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ResetPasswordStep1", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class ResetPasswordStep1Request
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Authentication.SendResetPasswordRequest request;

        public ResetPasswordStep1Request()
        {
        }

        public ResetPasswordStep1Request(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Authentication.SendResetPasswordRequest request)
        {
            this.request = request;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ResetPasswordStep1Response", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class ResetPasswordStep1Response
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public string ResetPasswordStep1Result;

        public ResetPasswordStep1Response()
        {
        }

        public ResetPasswordStep1Response(string ResetPasswordStep1Result)
        {
            this.ResetPasswordStep1Result = ResetPasswordStep1Result;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ResetPasswordStep2", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class ResetPasswordStep2Request
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Authentication.ResetPasswordRequest request;

        public ResetPasswordStep2Request()
        {
        }

        public ResetPasswordStep2Request(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Authentication.ResetPasswordRequest request)
        {
            this.request = request;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ResetPasswordStep2Response", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class ResetPasswordStep2Response
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Authentication.Unit ResetPasswordStep2Result;

        public ResetPasswordStep2Response()
        {
        }

        public ResetPasswordStep2Response(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Authentication.Unit ResetPasswordStep2Result)
        {
            this.ResetPasswordStep2Result = ResetPasswordStep2Result;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IAuthenticationSoapEndpointServiceChannel : TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Authentication.IAuthenticationSoapEndpointService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class AuthenticationSoapEndpointServiceClient : System.ServiceModel.ClientBase<TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Authentication.IAuthenticationSoapEndpointService>, TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Authentication.IAuthenticationSoapEndpointService
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public AuthenticationSoapEndpointServiceClient() :
                base(AuthenticationSoapEndpointServiceClient.GetDefaultBinding(), AuthenticationSoapEndpointServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpsBinding.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public AuthenticationSoapEndpointServiceClient(EndpointConfiguration endpointConfiguration) :
                base(AuthenticationSoapEndpointServiceClient.GetBindingForEndpoint(endpointConfiguration), AuthenticationSoapEndpointServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public AuthenticationSoapEndpointServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(AuthenticationSoapEndpointServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public AuthenticationSoapEndpointServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(AuthenticationSoapEndpointServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public AuthenticationSoapEndpointServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public System.Threading.Tasks.Task<TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Authentication.LoginResponse> LoginAsync(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Authentication.LoginRequest1 request)
        {
            return base.Channel.LoginAsync(request);
        }

        public System.Threading.Tasks.Task<TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Authentication.ResetPasswordStep1Response> ResetPasswordStep1Async(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Authentication.ResetPasswordStep1Request request)
        {
            return base.Channel.ResetPasswordStep1Async(request);
        }

        public System.Threading.Tasks.Task<TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Authentication.ResetPasswordStep2Response> ResetPasswordStep2Async(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Authentication.ResetPasswordStep2Request request)
        {
            return base.Channel.ResetPasswordStep2Async(request);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding))
            {
                System.ServiceModel.BasicHttpsBinding result = new System.ServiceModel.BasicHttpsBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding))
            {
                return new System.ServiceModel.EndpointAddress("https://genericapi.francecentral.cloudapp.azure.com/soap-api/authentication");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AuthenticationSoapEndpointServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpsBinding);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AuthenticationSoapEndpointServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpsBinding);
        }

        public enum EndpointConfiguration
        {

            BasicHttpsBinding,
        }
    }
}
