//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.ITicketSoapEndpo" +
        "intService")]
    public interface ITicketSoapEndpointService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ITicketSoapEndpointService/CreateTicket", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.CreateTicketResponse> CreateTicketAsync(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.CreateTicketRequest1 request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ITicketSoapEndpointService/GetTicketDetails", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.GetTicketDetailsResponse1> GetTicketDetailsAsync(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.GetTicketDetailsRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ITicketSoapEndpointService/GetTicketDocument", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.GetTicketDocumentResponse1> GetTicketDocumentAsync(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.GetTicketDocumentRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ITicketSoapEndpointService/UpdateTicket", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.UpdateTicketResponse> UpdateTicketAsync(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.UpdateTicketRequest1 request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ITicketSoapEndpointService/DeleteTicket", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.DeleteTicketResponse> DeleteTicketAsync(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.DeleteTicketRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ITicketSoapEndpointService/GetCurrentUserTicketsList", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.GetCurrentUserTicketsListResponse> GetCurrentUserTicketsListAsync(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.GetCurrentUserTicketsListRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ITicketSoapEndpointService/GetUserTicketsList", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.GetUserTicketsListResponse1> GetUserTicketsListAsync(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.GetUserTicketsListRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ITicketSoapEndpointService/GetTicketsList", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.GetTicketsListResponse1> GetTicketsListAsync(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.GetTicketsListRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class CreateTicketRequest
    {

        private string userIdField;

        private string routeIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string UserId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string RouteId
        {
            get
            {
                return this.routeIdField;
            }
            set
            {
                this.routeIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class TicketLookupModel
    {

        private string idField;

        private string userIdField;

        private string routeIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string UserId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string RouteId
        {
            get
            {
                return this.routeIdField;
            }
            set
            {
                this.routeIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class GetTicketsListResponse
    {
        private TicketLookupModel[] ticketsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(IsNullable = true)]
        public TicketLookupModel[] Tickets
        {
            get
            {
                return this.ticketsField;
            }
            set
            {
                this.ticketsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class UserTicketRouteStationLookupModel
    {

        private string idField;

        private string nameField;

        private double latitudeField;

        private double longitudeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public double Latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public double Longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class UserTicketRouteLookupModel
    {

        private string idField;

        private UserTicketRouteStationLookupModel fromField;

        private UserTicketRouteStationLookupModel toField;

        private System.DateTime departureTimeField;

        private string durationField;

        private double distanceField;

        private double ticketPriceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public UserTicketRouteStationLookupModel From
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public UserTicketRouteStationLookupModel To
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public System.DateTime DepartureTime
        {
            get
            {
                return this.departureTimeField;
            }
            set
            {
                this.departureTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration", Order = 4)]
        public string Duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public double Distance
        {
            get
            {
                return this.distanceField;
            }
            set
            {
                this.distanceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public double TicketPrice
        {
            get
            {
                return this.ticketPriceField;
            }
            set
            {
                this.ticketPriceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class UserTicketLookupModel
    {

        private string idField;

        private string userIdField;

        private UserTicketRouteLookupModel routeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string UserId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public UserTicketRouteLookupModel Route
        {
            get
            {
                return this.routeField;
            }
            set
            {
                this.routeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class GetUserTicketsListResponse
    {

        private UserTicketLookupModel[] ticketsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem(IsNullable = true)]
        public UserTicketLookupModel[] Tickets
        {
            get
            {
                return this.ticketsField;
            }
            set
            {
                this.ticketsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class Unit
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class UpdateTicketRequest
    {

        private string idField;

        private string userIdField;

        private string routeIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string UserId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string RouteId
        {
            get
            {
                return this.routeIdField;
            }
            set
            {
                this.routeIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class GetTicketDocumentResponse
    {

        private string idField;

        private byte[] documentField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary", Order = 1)]
        public byte[] Document
        {
            get
            {
                return this.documentField;
            }
            set
            {
                this.documentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class TicketStationDetailsModel
    {

        private string idField;

        private string nameField;

        private double latitudeField;

        private double longitudeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public double Latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public double Longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class TicketRouteDetailsModel
    {

        private string idField;

        private TicketStationDetailsModel fromField;

        private TicketStationDetailsModel toField;

        private System.DateTime departureTimeField;

        private string durationField;

        private double distanceField;

        private double ticketPriceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public TicketStationDetailsModel From
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public TicketStationDetailsModel To
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public System.DateTime DepartureTime
        {
            get
            {
                return this.departureTimeField;
            }
            set
            {
                this.departureTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration", Order = 4)]
        public string Duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public double Distance
        {
            get
            {
                return this.distanceField;
            }
            set
            {
                this.distanceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public double TicketPrice
        {
            get
            {
                return this.ticketPriceField;
            }
            set
            {
                this.ticketPriceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class GetTicketDetailsResponse
    {

        private string idField;

        private System.DateTime createdOnField;

        private string createdByField;

        private System.DateTime lastSavedOnField;

        private string lastSavedByField;

        private string userIdField;

        private TicketRouteDetailsModel routeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public System.DateTime CreatedOn
        {
            get
            {
                return this.createdOnField;
            }
            set
            {
                this.createdOnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 2)]
        public string CreatedBy
        {
            get
            {
                return this.createdByField;
            }
            set
            {
                this.createdByField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public System.DateTime LastSavedOn
        {
            get
            {
                return this.lastSavedOnField;
            }
            set
            {
                this.lastSavedOnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 4)]
        public string LastSavedBy
        {
            get
            {
                return this.lastSavedByField;
            }
            set
            {
                this.lastSavedByField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string UserId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public TicketRouteDetailsModel Route
        {
            get
            {
                return this.routeField;
            }
            set
            {
                this.routeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class IdRequest
    {

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class IdResponse
    {

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "CreateTicket", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class CreateTicketRequest1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.CreateTicketRequest ticket;

        public CreateTicketRequest1()
        {
        }

        public CreateTicketRequest1(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.CreateTicketRequest ticket)
        {
            this.ticket = ticket;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "CreateTicketResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class CreateTicketResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.IdResponse CreateTicketResult;

        public CreateTicketResponse()
        {
        }

        public CreateTicketResponse(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.IdResponse CreateTicketResult)
        {
            this.CreateTicketResult = CreateTicketResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetTicketDetails", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetTicketDetailsRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.IdRequest id;

        public GetTicketDetailsRequest()
        {
        }

        public GetTicketDetailsRequest(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.IdRequest id)
        {
            this.id = id;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetTicketDetailsResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetTicketDetailsResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.GetTicketDetailsResponse GetTicketDetailsResult;

        public GetTicketDetailsResponse1()
        {
        }

        public GetTicketDetailsResponse1(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.GetTicketDetailsResponse GetTicketDetailsResult)
        {
            this.GetTicketDetailsResult = GetTicketDetailsResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetTicketDocument", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetTicketDocumentRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.IdRequest id;

        public GetTicketDocumentRequest()
        {
        }

        public GetTicketDocumentRequest(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.IdRequest id)
        {
            this.id = id;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetTicketDocumentResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetTicketDocumentResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.GetTicketDocumentResponse GetTicketDocumentResult;

        public GetTicketDocumentResponse1()
        {
        }

        public GetTicketDocumentResponse1(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.GetTicketDocumentResponse GetTicketDocumentResult)
        {
            this.GetTicketDocumentResult = GetTicketDocumentResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "UpdateTicket", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class UpdateTicketRequest1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.UpdateTicketRequest ticket;

        public UpdateTicketRequest1()
        {
        }

        public UpdateTicketRequest1(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.UpdateTicketRequest ticket)
        {
            this.ticket = ticket;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "UpdateTicketResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class UpdateTicketResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.Unit UpdateTicketResult;

        public UpdateTicketResponse()
        {
        }

        public UpdateTicketResponse(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.Unit UpdateTicketResult)
        {
            this.UpdateTicketResult = UpdateTicketResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "DeleteTicket", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class DeleteTicketRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.IdRequest id;

        public DeleteTicketRequest()
        {
        }

        public DeleteTicketRequest(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.IdRequest id)
        {
            this.id = id;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "DeleteTicketResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class DeleteTicketResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.Unit DeleteTicketResult;

        public DeleteTicketResponse()
        {
        }

        public DeleteTicketResponse(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.Unit DeleteTicketResult)
        {
            this.DeleteTicketResult = DeleteTicketResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetCurrentUserTicketsList", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetCurrentUserTicketsListRequest
    {

        public GetCurrentUserTicketsListRequest()
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetCurrentUserTicketsListResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetCurrentUserTicketsListResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.GetUserTicketsListResponse GetCurrentUserTicketsListResult;

        public GetCurrentUserTicketsListResponse()
        {
        }

        public GetCurrentUserTicketsListResponse(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.GetUserTicketsListResponse GetCurrentUserTicketsListResult)
        {
            this.GetCurrentUserTicketsListResult = GetCurrentUserTicketsListResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetUserTicketsList", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetUserTicketsListRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.IdRequest id;

        public GetUserTicketsListRequest()
        {
        }

        public GetUserTicketsListRequest(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.IdRequest id)
        {
            this.id = id;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetUserTicketsListResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetUserTicketsListResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.GetUserTicketsListResponse GetUserTicketsListResult;

        public GetUserTicketsListResponse1()
        {
        }

        public GetUserTicketsListResponse1(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.GetUserTicketsListResponse GetUserTicketsListResult)
        {
            this.GetUserTicketsListResult = GetUserTicketsListResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetTicketsList", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetTicketsListRequest
    {

        public GetTicketsListRequest()
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetTicketsListResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetTicketsListResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.GetTicketsListResponse GetTicketsListResult;

        public GetTicketsListResponse1()
        {
        }

        public GetTicketsListResponse1(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.GetTicketsListResponse GetTicketsListResult)
        {
            this.GetTicketsListResult = GetTicketsListResult;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ITicketSoapEndpointServiceChannel : TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.ITicketSoapEndpointService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class TicketSoapEndpointServiceClient : System.ServiceModel.ClientBase<TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.ITicketSoapEndpointService>, TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.ITicketSoapEndpointService
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public TicketSoapEndpointServiceClient() :
                base(TicketSoapEndpointServiceClient.GetDefaultBinding(), TicketSoapEndpointServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpsBinding.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public TicketSoapEndpointServiceClient(EndpointConfiguration endpointConfiguration) :
                base(TicketSoapEndpointServiceClient.GetBindingForEndpoint(endpointConfiguration), TicketSoapEndpointServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public TicketSoapEndpointServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(TicketSoapEndpointServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public TicketSoapEndpointServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(TicketSoapEndpointServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public TicketSoapEndpointServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public System.Threading.Tasks.Task<TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.CreateTicketResponse> CreateTicketAsync(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.CreateTicketRequest1 request)
        {
            return base.Channel.CreateTicketAsync(request);
        }

        public System.Threading.Tasks.Task<TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.GetTicketDetailsResponse1> GetTicketDetailsAsync(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.GetTicketDetailsRequest request)
        {
            return base.Channel.GetTicketDetailsAsync(request);
        }

        public System.Threading.Tasks.Task<TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.GetTicketDocumentResponse1> GetTicketDocumentAsync(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.GetTicketDocumentRequest request)
        {
            return base.Channel.GetTicketDocumentAsync(request);
        }

        public System.Threading.Tasks.Task<TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.UpdateTicketResponse> UpdateTicketAsync(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.UpdateTicketRequest1 request)
        {
            return base.Channel.UpdateTicketAsync(request);
        }

        public System.Threading.Tasks.Task<TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.DeleteTicketResponse> DeleteTicketAsync(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.DeleteTicketRequest request)
        {
            return base.Channel.DeleteTicketAsync(request);
        }

        public System.Threading.Tasks.Task<TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.GetCurrentUserTicketsListResponse> GetCurrentUserTicketsListAsync(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.GetCurrentUserTicketsListRequest request)
        {
            return base.Channel.GetCurrentUserTicketsListAsync(request);
        }

        public System.Threading.Tasks.Task<TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.GetUserTicketsListResponse1> GetUserTicketsListAsync(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.GetUserTicketsListRequest request)
        {
            return base.Channel.GetUserTicketsListAsync(request);
        }

        public System.Threading.Tasks.Task<TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.GetTicketsListResponse1> GetTicketsListAsync(TrainsOnline.Desktop.Infrastructure.Services.SoapServices.Ticket.GetTicketsListRequest request)
        {
            return base.Channel.GetTicketsListAsync(request);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding))
            {
                System.ServiceModel.BasicHttpsBinding result = new System.ServiceModel.BasicHttpsBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding))
            {
                return new System.ServiceModel.EndpointAddress("https://genericapi.francecentral.cloudapp.azure.com/soap-api/ticket");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TicketSoapEndpointServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpsBinding);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TicketSoapEndpointServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpsBinding);
        }

        public enum EndpointConfiguration
        {

            BasicHttpsBinding,
        }
    }
}
